<article class="card prose">
    <p class="eyebrow">Legal</p>
    <h1>Terms of use</h1>
    <p class="muted">By creating an account you agree to these terms. The operator of this installation should review and adapt them.</p>

    <div class="alert alert-warning" role="note"><?= icon('alert') ?>
        <span><strong>Interview-use notice:</strong> Use this assistant only where external assistance, transcription or scanning is permitted by the interviewer, employer, examiner, platform rules, or applicable requirements.</span>
    </div>

    <h2>Acceptable use</h2>
    <ul>
        <li>You are responsible for making sure that using transcription or AI assistance is allowed in each interview or assessment, and for obtaining any consent required to transcribe other people's speech.</li>
        <li>Scanning a question paper, form or assessment is your responsibility too. Only scan material you are permitted to photograph and to get help with, and do not submit AI-written answers where that is not allowed.</li>
        <li>Do not use the service to misrepresent your qualifications or experience. Suggestions are designed to help you structure answers from your own CV — not to invent experience.</li>
        <li>Do not upload content you do not have the right to use, or attempt to disrupt or misuse the service.</li>
    </ul>

    <h2>AI-generated content</h2>
    <p>Answer guidance is generated by AI and may be incomplete or incorrect. Always review suggestions and answer honestly in your own words. No outcome (such as a job offer) is guaranteed.</p>

    <h2>Your content</h2>
    <p>You keep ownership of your CV, job descriptions, scanned questions and answers. You grant the service permission to process them solely to provide the features you use. You can delete your data at any time.</p>

    <h2>Availability</h2>
    <p>The service relies on third-party AI providers and may be unavailable or slow at times. Features may change.</p>

    <h2>Liability</h2>
    <p>The service is provided “as is”, to the maximum extent permitted by law, without warranties of any kind.</p>
</article>
